name: spurious-cue
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.10.11=h06a4308_0
  - certifi=2022.9.24=py37h06a4308_0
  - cffi=1.15.1=py37h5eee18b_2
  - cryptography=38.0.1=py37h9ce1e76_0
  - cuda=11.6.2=0
  - cuda-cccl=11.6.55=hf6102b2_0
  - cuda-command-line-tools=11.6.2=0
  - cuda-compiler=11.6.2=0
  - cuda-cudart=11.6.55=he381448_0
  - cuda-cudart-dev=11.6.55=h42ad0f4_0
  - cuda-cuobjdump=11.6.124=h2eeebcb_0
  - cuda-cupti=11.6.124=h86345e5_0
  - cuda-cuxxfilt=11.6.124=hecbf4f6_0
  - cuda-driver-dev=11.6.55=0
  - cuda-gdb=11.8.86=0
  - cuda-libraries=11.6.2=0
  - cuda-libraries-dev=11.6.2=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=11.8.86=0
  - cuda-nsight-compute=11.8.0=0
  - cuda-nvcc=11.6.124=hbba6d2d_0
  - cuda-nvdisasm=11.8.86=0
  - cuda-nvml-dev=11.6.55=haa9ef22_0
  - cuda-nvprof=11.8.87=0
  - cuda-nvprune=11.6.124=he22ec0a_0
  - cuda-nvrtc=11.6.124=h020bade_0
  - cuda-nvrtc-dev=11.6.124=h249d397_0
  - cuda-nvtx=11.6.124=h0630a44_0
  - cuda-nvvp=11.8.87=0
  - cuda-runtime=11.6.2=0
  - cuda-samples=11.6.101=h8efea70_0
  - cuda-sanitizer-api=11.8.86=0
  - cuda-toolkit=11.6.2=0
  - cuda-tools=11.6.2=0
  - cuda-visual-tools=11.6.2=0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - gds-tools=1.4.0.31=0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py37h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcufile=1.4.0.31=0
  - libcufile-dev=1.4.0.31=0
  - libcurand=10.3.0.86=0
  - libcurand-dev=10.3.0.86=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.8=h7f8727e_5
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.4.0=hecacb30_2
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.3=h5eee18b_3
  - nettle=3.7.3=hbbd107a_1
  - nsight-compute=2022.3.0.22=0
  - numpy-base=1.21.5=py37ha15fc14_3
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1s=h7f8727e_0
  - pip=22.2.2=py37h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py37_1
  - python=3.7.15=h7a1cb2a_1
  - pytorch=1.13.0=py3.7_cuda11.6_cudnn8.3.2_0
  - pytorch-cuda=11.6=h867d48c_0
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py37h06a4308_0
  - setuptools=65.5.0=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.0=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.13.0=py37_cu116
  - torchvision=0.14.0=py37_cu116
  - typing_extensions=4.3.0=py37h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - altair==4.2.0
    - astor==0.8.1
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - attrs==22.1.0
    - backports-zoneinfo==0.2.1
    - base58==2.1.1
    - black==21.12b0
    - blinker==1.5
    - brotli==1.0.9
    - cachetools==5.2.0
    - charset-normalizer==2.1.1
    - click==7.1.2
    - cycler==0.11.0
    - datasets==2.7.1
    - decorator==5.1.1
    - dill==0.3.6
    - docker-pycreds==0.4.0
    - entrypoints==0.4
    - exceptiongroup==1.0.4
    - filelock==3.8.0
    - flake8==5.0.4
    - fonttools==4.38.0
    - frozenlist==1.3.3
    - fsspec==2022.11.0
    - gitdb==4.0.10
    - gitpython==3.1.29
    - huggingface-hub==0.11.0
    - importlib-metadata==4.2.0
    - importlib-resources==5.10.0
    - inflate64==0.3.1
    - iniconfig==1.1.1
    - isort==5.8.0
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonschema==4.17.1
    - kiwisolver==1.4.4
    - markupsafe==2.1.1
    - matplotlib==3.5.3
    - mccabe==0.7.0
    - multidict==6.0.2
    - multiprocess==0.70.14
    - multivolumefile==0.2.3
    - mypy-extensions==0.4.3
    - numpy==1.21.6
    - packaging==21.3
    - pandas==1.3.5
    - pathspec==0.10.2
    - pathtools==0.1.2
    - pillow==9.3.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==2.5.4
    - plotly==5.11.0
    - pluggy==1.0.0
    - promise==2.3
    - promptsource==0.2.3
    - protobuf==4.21.9
    - psutil==5.9.4
    - py7zr==0.20.2
    - pyarrow==10.0.1
    - pybcj==1.0.1
    - pycodestyle==2.9.1
    - pycryptodomex==3.15.0
    - pydeck==0.8.0
    - pyflakes==2.5.0
    - pyparsing==3.0.9
    - pyppmd==1.0.0
    - pyrsistent==0.19.2
    - pytest==7.2.0
    - python-dateutil==2.8.2
    - pytz==2022.6
    - pytz-deprecation-shim==0.1.0.post0
    - pyyaml==6.0
    - pyzstd==0.15.3
    - regex==2022.10.31
    - responses==0.18.0
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.12.1
    - sentencepiece==0.1.97
    - sentry-sdk==1.11.1
    - setproctitle==1.3.2
    - shortuuid==1.0.11
    - smmap==5.0.0
    - streamlit==0.82.0
    - tenacity==8.1.0
    - texttable==1.6.7
    - threadpoolctl==3.1.0
    - tokenizers==0.13.2
    - toml==0.10.2
    - tomli==1.2.3
    - toolz==0.12.0
    - tornado==6.2
    - tqdm==4.64.1
    - transformers==4.24.0
    - typed-ast==1.5.4
    - typing-extensions==4.4.0
    - tzdata==2022.6
    - tzlocal==4.2
    - urllib3==1.26.13
    - validators==0.20.0
    - wandb==0.13.5
    - watchdog==2.1.9
    - xxhash==3.1.0
    - yarl==1.8.1
    - zipp==3.11.0
prefix: /home/seacow/miniconda3/envs/spurious-cue
